[package]
name = "Rust"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"

# cargo run --bin all_together
[[bin]]
name = "all_together"
path = "src/all_together.rs"
